# Generated by Django 5.2.16 on 2026-07-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_post_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
    ]
