# Generated by Django 5.2.16 on 2026-08-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='ADMISSION OPEN', help_text='Small top badge tag (e.g. ADMISSION OPEN)', max_length=50)),
                ('title', models.CharField(default='April Session 2027', help_text='Main heading title', max_length=255)),
                ('description', models.TextField(default="Secure your spot in many of Japan's top language schools and colleges.", help_text='Detailed modal message')),
                ('highlight_text', models.CharField(blank=True, default='Apply now for Student Visa!', help_text='Highlighted text line', max_length=255)),
                ('button_text', models.CharField(default='Start Application', help_text='Call to Action button label', max_length=100)),
                ('button_link', models.CharField(default='/contact', help_text='URL link for the button (e.g. /contact)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only active popup announcement will be displayed on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup Announcement',
                'verbose_name_plural': 'Popup Announcements',
                'ordering': ['-updated_at'],
            },
        ),
    ]
