# Generated by Django 5.2.16 on 2026-08-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_popupannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupannouncement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional popup banner image', null=True, upload_to='popups/'),
        ),
    ]
